set shell := ["pwsh.exe", "-CommandWithArgs"]
set dotenv-load := true

build-client:
    fyne package

[working-directory: 'notify']
build-notify:
    go build -o ../notify.exe -ldflags -H=windowsgui .
