-- arguments: (store_id int)
SELECT
    CAST(G.CODE AS BIGINT) AS CODE,
    ISNULL(CAST((
        SELECT TOP 1
            KIZ.GTIN
        FROM KIZ_2_DOCUMENT_ITEM KDI
                 JOIN KIZ ON KIZ.ID_KIZ_GLOBAL=KDI.ID_KIZ_GLOBAL
        WHERE
            KDI.ID_DOCUMENT_ITEM_ADD = L.ID_DOCUMENT_ITEM_ADD
    ) AS BIGINT), 0) AS GTIN,

    CAST(G.NAME AS VARCHAR(250)) AS NAME,
    CAST(L.QUANTITY_REM AS INT) AS COUNT,
    CAST(FLOOR(L.PRICE_SAL*100) AS INT) AS PRICE,
    --CAST((L.PRICE_SAL - FLOOR(L.PRICE_SAL)) * 100 AS INT) AS KOP,

    ISNULL(P.NAME, '') AS PRODUCER,
    ISNULL(CR.NAME, '') AS COUNTRY,
    ISNULL(G.DESCRIPTION, '') AS DESCRIPTION

FROM LOT L
    inner join GOODS G on L.ID_GOODS = G.ID_GOODS
    inner join PRODUCER P on P.ID_PRODUCER = G.ID_PRODUCER
    inner join STORE ST on ST.ID_STORE = L.ID_STORE
    inner join COUNTRY CR on CR.ID_COUNTRY = P.ID_COUNTRY

WHERE
    L.QUANTITY_REM > 0
  and ST.ID_CONTRACTOR = DBO.FN_CONST_CONTRACTOR_SELF()
  and l.id_store = ?
  --and st.MNEMOCODE in ('О-4601')

ORDER BY G.CODE



